### ISSUE TITLE
SuperTokens.init: Add sameSite to cookie options

### ISSUE THREAD

**Issue by enlightenedmouse** [supertokens/supertokens-node-mysql-ref-jwt#24]
Chrome Warnings:
A cookie associated with a cross-site resource at http://site-url-here/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None`.

If we could add the mentioned cookie attribute to the init options i.e. along with cookie.domain etc., that would be great. Thx.

**Comment by rishabhpoddar** [comment]
This issue has been fixed in version v5.0.2 which has now been released.

We have set the SameSite attribute to "None" for all cookies managed by SuperTokens so this is not a breaking change. This is not a security issue since SuperTokens already has inbuilt CSRF protection.

To see this warning go away in your chrome console, you will have to re-login currently logged in users.

Please comment on this issue if this error still persists.

**Comment by enlightenedmouse** [comment]
Hi @rishabhpoddar,

Please reconsider adding this to the cookie options; local development over http is restricted if we cannot set SameSite = "Lax" since the cookies do not have the "Secure" setting and get blocked by the browser.

On that note, when we do make a request over https, the idRefreshTokenCookieKey is not being sent with the "Secure" flag so it too is being blocked by the browser and causes 401 responses.

Both issues are related to https://blog.chromium.org/2019/10/developers-get-ready-for-new.html

Your help is appreciated,
Thanks.

**Comment by rishabhpoddar** [comment]
Alright. I will add the sameSite option in the cookie options. Thanks!

>  the idRefreshTokenCookieKey is not being sent with the "Secure"
There are two cookies that store the id refresh token:
- `sIdRefreshToken`: Set by the backend SDK
- `sIRTFrontend`: Set by the frontend SDK

`sIdRefreshToken` will get the same `sameSite` option as what you set for once I enable this config. And `sIRTFrontend` doesn't need to be sent to the backend - it's only for frontend use. 

So when I make this change of `sameSite` being configurable, then it should solve all these issues.

**Comment by rishabhpoddar** [comment]
I have made the relevant changes in [this](https://github.com/supertokens/supertokens-node-mysql-ref-jwt/commit/578ca38d017d6f37384b7b849f4e9196b898cad0) commit.

In short, I have added the following to the `config` object:
```
config = {
    ...
    cookie: {
        ...
        sameSite?: "strict" | "lax" | "none"
    }
}
```

If you do not provide this, it will be `none` (hence non breaking). If you do provide this, all the cookies issued by our library from the backend will have this attribute as what you have set.

Will this solve your problem? If yes, then I can push this npm and make the docs changes. Otherwise, please elaborate more on your issue.

**Comment by rishabhpoddar** [comment]
I have pushed this to npm. Feel free to comment if this issue is still not resolved.

**Comment by enlightenedmouse** [comment]
Hi @rishabhpoddar,
Thanks for the update. It has definitely helped me with my development environment however our prod environment still has the issue with the sIdRefreshToken cookie not being sent as secure and is getting blocked.

Please see the attached image from the chrome browser:
<img width="1243" alt="Screen Shot 2020-03-14 at 1 48 59 PM" src="https://user-images.githubusercontent.com/25255126/76687650-385cef00-65fc-11ea-9137-80b68541e5d9.png">

Let me know your thoughts. Thx.

**Comment by rishabhpoddar** [comment]
Hi @enlightenedmouse 
I have pushed the latest version v5.0.4 with this fix. Now the `idRefreshToken` will have the same secure flag as what you set in the `config` object. I hope this has solved this issue.

To see this change, you may have to relogin from your application.

**Comment by enlightenedmouse** [comment]
It does the trick : ) Thanks again.
